# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: '/InfoVisDHGraz'

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en


# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/Vienna

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Workshop on Information Visualization in the (Digital) Humanities                          # the main title

tagline: 27th-28th of October 2022, University of Graz    # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  Information visualization has become an integral part of the (digital) humanities and has undergone a rapid development during the last years. One of the advantages of this development is that the collection, analysis, and visualization of information take place no longer in separate processes, but are often undertaken by one and the same person or research group. This has drawn new attention to the usefulness and functionality in general and raises the question of the relationship between researchers and the objects of study. On the one hand, visualizations can provide useful insights and new perspectives. On the other hand, their applicability can be limited by the researcher’s scientific aims, academic education, and their technical capabilities. A conscious approach allows us to uncover the advantages and disadvantages of these relationships between the object of study and the researcher. 
  The Centre for Information Modelling in cooperation with the Department of Translation Studies at the University of Graz organizes a workshop to discuss this relation between researchers and the objects they visualize based on real use cases. Starting from an increased awareness of the relation between agent and object, we want to reflect on the researcher's point of view and how it practically influences the way we develop new visuals. Are they based on the information and its characteristic traits or rather on the needs of its further use? How do researchers influence their own visualizations and are they aware of their subjective approach?
  To answer these questions, a jury of internationally recognised experts will be formed for the workshop, which will subject the submitted examples to a structural analysis and combine it with a corresponding discussion. The participants of the jury deliberately cover different areas (technical, academic, artistic) and thus enable a well-founded analysis of the effectiveness.
  The workshop is aimed at experienced researchers as well as beginners who want to receive expert comments on their individual implementations. We propose to address finished as well as works in progress from scholars in the (digital) humanities.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://chpollin.github.io/InfoVisDHGraz'

github:
  username: chpollin             # change to your github username

twitter:
  username: LurchPollin          # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Florian Atzenhofer-Baumgartner
  email: christopher.pollin@uni-graz.at             # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username      # change to your twitter homepage
    - https://github.com/username       # change to your github homepage

google_site_verification:               # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id:                 # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint:   # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path:       # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode:  light # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: 

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/icon.png

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active:         # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo:              # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping:           # optional, default to 'pathname'
    input_position:    # optional, default to 'bottom'
    lang:              # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled:      # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env:          # [development|production]

pwa:
  enabled: true   # the option for PWA feature

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:   # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

# CP https://github.com/MihajloNesic/jekyll-pdf-embed
plugins:
  - jekyll-pdf-embed

defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
